- name: Configuring the {{COMPONENT}} repo
  ansible.builtin.copy:
    src: redis.repo
    dest: /etc/yum.repos.d/redis.repo  

- name: Installing {{COMPONENT}}
  ansible.builtin.package:
    name: redis-6.2.14
    state: present

- name: Configuring the {{COMPONENT}} visibility
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: starting {{COMPONENT}}
  systemd:
    name: redis
    state: restarted
    enabled: yes

- name: Configuring name
  ansible.builtin.include_role:
    name: common
    tasks_from: set_name