- name: Configuring the {{COMPONENT}} repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo  

- name: Installing {{COMPONENT}}
  ansible.builtin.package:
    name: mongodb-org
    state: present

- name: starting {{COMPONENT}}
  systemd:
    name: mongod
    state: restarted
    enabled: yes

- name: Configuring service name 
  ansible.builtin.shell: set-hostname {{COMPONENT}}-{{ENV}}