- name: Demo on vars usage
  hosts: all      ## Groupname in the inventory file
  vars:                                               #Global variables: All the tasks of this play can access this variable 
    URL: play.google.com
  vars_prompt:
    - name: URNAME
      promt: Enter your name
  tasks:
    - name: Printing the variable
      ansible.builtin.debug:
        msg: value of the variable is {{URL}}

    - name: Demo on using local variable 
      ansible.builtin.debug:
        msg: value of the URL's is {{URL}}
      vars:
        URL: task.google.com

    - name: Demo on using unrelated variable
      ansible.builtin.debug:
        msg: value of CLIURL is {{CLIURL}}

    - name: printing prompt variable
      ansible.builtin.debug:
        msg: Name of the person is {{name}}


## PS - if you try to print an variable that is not declared, then it will throw an error

# variable precedence:

### local variable > globe variable
