- name: Demo on vars usage
  hosts: all      ## Groupname in the inventory file
  vars:                                               #Global variables: All the tasks of this play can access this variable 
    URL: play.google.com
  tasks:
    - name: Printing the variable
      ansible.builtin.debug:
        msg: value of the variable is {{URL}}

    - name: Printing the variable name 
      ansible.builtin.debug:
        msg: value of the URL's is {{URL}}

