- name: Demo on vars usage
  hosts: all      ## Groupname in the inventory file
  vars:                                               #Global variables: All the tasks of this play can access this variable 
    URL: play.google.com
  tasks:
    - name: Printing the variable
      ansible.builtin.debug:
        msg: value of the variable is {{URL}}

# Note: If you would just like to print a variable then enclose the variable in "{{varName}}" & there is no single quote concept.
#.... & if the variable is present in between the string of words, you don't have to enclose them in quotes.