- name: copying the systemd file
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service  

- name: starting {{COMPONENT}}
  systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Configuring service name 
  ansible.builtin.shell: set-hostname {{COMPONENT}}-{{ENV}}